src/Entity/Piece.php
<?php

namespace App\Entity;

use App\Repository\PieceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: PieceRepository::class)]
#[Vich\Uploadable]
class Piece
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;
    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageName = null;
    #[ORM\Column(length: 555)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $Quantite_en_stock = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\ManyToOne(inversedBy: 'pieces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicule $id_vehicule = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

  

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getQuantiteEnStock(): ?int
    {
        return $this->Quantite_en_stock;
    }

    public function setQuantiteEnStock(int $Quantite_en_stock): static
    {
        $this->Quantite_en_stock = $Quantite_en_stock;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getIdVehicule(): ?Vehicule
    {
        return $this->id_vehicule;
    }

    public function setIdVehicule(?Vehicule $id_vehicule): static
    {
        $this->id_vehicule = $id_vehicule;

        return $this;
    }
}

src/Form/PieceType.php
<?php

namespace App\Form;

use App\Entity\Piece;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PieceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('imageFile', VichImageType::class, [
                'label'=>'photo du vehicule'
            ])
            ->add('Description')
            ->add('Quantite_en_stock')
            ->add('prix')
            ->add('id_vehicule')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Piece::class,
        ]);
    }
}

src/Controller/PieceController.php
<?php

namespace App\Controller;

use App\Entity\Piece;
use App\Form\PieceType;
use App\Repository\PieceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/piece')]
class PieceController extends AbstractController
{
    #[Route('/', name: 'app_piece_index', methods: ['GET'])]
    public function index(PieceRepository $pieceRepository): Response
    {
        return $this->render('piece/index.html.twig', [
            'pieces' => $pieceRepository->findAll(),
        ]);
    }
    #[Route('/api/piece', name: 'api_piece', methods: ['GET'])]
    public function apiIndex(PieceRepository $pieceRepository): JsonResponse
    {
        $pieces = $pieceRepository->findAll();
        $data = [];

        foreach ($pieces as $piece) {
            $data[] = [
                'id' => $piece->getId(),
                'imageName' => $piece->getImageName(),
                'nom' => $piece->getNom(),
                'description' => $piece->getDescription(),
                'stock' => $piece->getQuantiteEnStock(),
                'prix' => $piece->getPrix()
            ];
        }

        return new JsonResponse($data);
    }
    #[Route('/api/last-Piece', name:'api_last_Piece', methods:['GET'])]
    public function getLastPiece(PieceRepository $pieceRepository): JsonResponse
    {
        $piece = $pieceRepository->findLastAdded();

        if (!$piece) {
            return new JsonResponse(null, 404);
        }

        $data = [
            'id' => $piece->getId(),
            'imageName' => $piece->getImageName(),
            'nom' => $piece->getNom(),
            'description' => $piece->getDescription(),
            'stock' => $piece->getQuantiteEnStock(),
            'prix' => $piece->getPrix()
        ];

        return new JsonResponse($data);
    }
    #[Route('/new', name: 'app_piece_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $piece = new Piece();
        $form = $this->createForm(PieceType::class, $piece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($piece);
            $entityManager->flush();

            return $this->redirectToRoute('app_piece_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('piece/new.html.twig', [
            'piece' => $piece,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_piece_show', methods: ['GET'])]
    public function show(Piece $piece): Response
    {
        return $this->render('piece/show.html.twig', [
            'piece' => $piece,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_piece_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Piece $piece, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PieceType::class, $piece);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_piece_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('piece/edit.html.twig', [
            'piece' => $piece,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_piece_delete', methods: ['POST'])]
    public function delete(Request $request, Piece $piece, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$piece->getId(), $request->request->get('_token'))) {
            $entityManager->remove($piece);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_piece_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/piece/_delete_form.html.twig
<form method="post" action="{{ path('app_piece_delete', {'id': piece.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ piece.id) }}">
    <button class="btn">Delete</button>
</form>

templates/piece/_form.html.twig
{{ form_start(form, {'attr': {'class': 'p-5 bg-white rounded shadow'}}) }}

    <div class="form-group">
        {{ form_label(form.nom, 'Nom', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.nom) }}
    </div>
  <div class="form-group">
        {{ form_label(form.id_vehicule, 'Marque', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.id_vehicule, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.id_vehicule) }}
    </div>
    <div class="form-group">
        {{ form_label(form.imageFile, 'Photo', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.imageFile, {'attr': {'class': 'form-control-file'}}) }}
        {{ form_errors(form.imageFile) }}
    </div>

    <div class="form-group">
        {{ form_label(form.Description, 'Description', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.Description, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.Description) }}
    </div>

    <div class="form-group">
        {{ form_label(form.Quantite_en_stock, 'Stock', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.Quantite_en_stock, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.Quantite_en_stock) }}
    </div>
     <div class="form-group">
        {{ form_label(form.prix, 'Prix', {'label_attr': {'class': 'form-label'}}) }}
        {{ form_widget(form.prix, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.prix) }}
    </div>

    <button type="submit" class="btn btn-dark btn-lg btn-block">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

{% block stylesheets %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .form-control {
            border-radius: 0;
        }
        .btn-primary {
            border-radius: 0;
        }
        .bg-white {
            border: 1px solid #ccc;
        }
    </style>
{% endblock %}
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

templates/piece/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Piece{% endblock %}

{% block body %}
    <h1>Edit Piece</h1>

    {{ include('piece/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_piece_index') }}">back to list</a>

    {{ include('piece/_delete_form.html.twig') }}
{% endblock %}

templates/piece/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piece index{% endblock %}

{% block body %}
    <h1>Piece index</h1>
<div id='pieces'></div>
    {# <table class="table w-100">
        <thead>
            <tr>
                
                <th>Nom</th>
                <th>vehicule</th>
                <th>Image</th>
                <th>Description</th>
                <th>stock</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for piece in pieces %}
            <tr>
                
                <td>{{ piece.nom }}</td>
              <td>{{  piece.idVehicule.marque }}  {{  piece.idVehicule.annee }}</td>
                 <td><img src="{{ asset('images/vehicule/' ~ piece.imageName) }}" width="10%"alt="piéce Image"/></td>
                <td>{{ piece.Description }}</td>
                <td>{{ piece.QuantiteEnStock }}</td>
                <td>{{ piece.prix }}</td>
                <td>
                    <a href="{{ path('app_piece_show', {'id': piece.id}) }}">show</a>
                    <a href="{{ path('app_piece_edit', {'id': piece.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}

    <a href="{{ path('app_piece_new') }}">Create new</a>
{% endblock %}

templates/piece/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Piece{% endblock %}

{% block body %}
    <h1>Create new Piece</h1>

    {{ include('piece/_form.html.twig') }}

    <a href="{{ path('app_piece_index') }}">back to list</a>
{% endblock %}

templates/piece/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Piece{% endblock %}

{% block body %}
 <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ asset('images/vehicule/' ~ piece.imageName) }}" alt="Véhicule Image" class="img-fluid rounded shadow">
            </div>
            <div class="col-md-6">
                <h1 class="mb-4">{{ piece.nom }} {{ piece.idVehicule.marque }}</h1>
                <table class="table table-bordered">
                    <tbody>
                       <tr>
                <th>Id</th>
                <td>{{ piece.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ piece.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ piece.Description }}</td>
            </tr>
            <tr>
                <th>stock</th>
                <td>{{ piece.QuantiteEnStock }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ piece.prix }} €</td>
            </tr>
                    </tbody>
                </table>
                <a href="{{ path('app_piece_index') }}" class="btn btn-secondary mb-2">Retour à la liste</a>
                <a href="{{ path('app_piece_edit', {'id': piece.id}) }}" class="btn btn-primary mb-2">Éditer</a>
                {{ include('piece/_delete_form.html.twig', {'button_class': 'btn-danger mb-2'}) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block stylesheets %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .table th, .table td {
            border-top: none;
        }
        .btn {
            border-radius: 0;
        }
    </style>
{% endblock %}